rust-embedded/riscv

src/register/misa.rs
Now it compiles (at least with warnings disabled..) for me.
=> Fix typo in register/misa.rs

src/asm.rs, src/interrupt.rs, src/register/mcause.rs, src/register/mcycle.rs, src/register/mcycleh.rs, src/register/mepc.rs, src/register/mie.rs, src/register/minstret.rs, src/register/minstreth.rs, src/register/mip.rs, src/register/misa.rs, src/register/mstatus.rs, src/register/mtvec.rs, src/register/mvendorid.rs
In the original riscv-rust fork the target arch was simply named
"riscv", but RISC-V support landed in Rust with "riscv32" as the arch
name instead.
Include "riscv64" optimistically for future-proofing.
=> fix target_arch conditionals to match "riscv32" and "riscv64"

src/asm.rs
`wfi` is safe, but the rest are not. Let's make them all unsafe until we have a better idea — the return types are wrong anyhow.
=> these raw instructions are unsafe

src/register/macros.rs, src/register/mie.rs, src/register/mstatus.rs, src/register/sie.rs, src/register/sstatus.rs
[rust-lang/rust#57882](https://github.com/rust-lang/rust/pull/57882) is modifying the `unused_doc_comments` lint to fire on mistakenly documented macro expansions. Note that these doc comments are not currently used, since they are eliminated when the macro is expanded. A crater run detected that this crate will break due to this change, likely because of the use of `deny(unused_doc_comments)` or `deny(warnings)`.
While this kind of breakage is allowed under Rust's stability guarantees, I am opening PRs to affected crates to reduce the impact.
This PR protects your crate from future breakage by moving the offending doc comments inside the macro invocations.
=> move doc comments inside macro invocations

CODE_OF_CONDUCT.md, README.md
More common name for the CPU architecture :smile:  Also update the copyright year.
Probably, if this is merged, you'd want to update the project description as well.
=> Rename RISCV to RISC-V in documentation

src/register/mod.rs, src/register/mstatus.rs, src/register/scause.rs, src/register/sstatus.rs, src/register/ucause.rs, src/register/uepc.rs, src/register/uie.rs, src/register/uip.rs, src/register/uscratch.rs, src/register/ustatus.rs, src/register/utval.rs, src/register/utvec.rs
Adds CSR handlers for user trap setup and handling registers.
Also unifies common shared types.
NOTE: untested, will test on real device ASAP
=> add user trap setup and handling registers

src/register/mtvec.rs
Some vendors (eg Nuclei) use reserved bits for they own interrupt handling.
=> Do not panic on unknown trap mode.

CHANGELOG.md, src/asm.rs, src/lib.rs, src/register/macros.rs
`asm!` was replaced with a different implementation on nightly, the old one is renamed into `llvm_asm!`
=> Replace asm! with llvm_asm!

CHANGELOG.md, src/register/stvec.rs, src/register/utvec.rs
See also: https://github.com/rust-embedded/riscv/pull/50#issuecomment-647012575
=> Fix {S,U}tvec::trap_mode() functions to match Mtvec::trap_mode()

.travis.yml, ci/install.sh, ci/script.sh, src/register/cycle.rs, src/register/cycleh.rs, src/register/instret.rs, src/register/instreth.rs, src/register/mstatus.rs, src/register/scause.rs, src/register/sstatus.rs, src/register/stval.rs, src/register/ucause.rs, src/register/utval.rs
This patch contains following parts: 
1. RISC-V privileged specification v1.10 defined `TVM`, `TW` and `TSR` bits in `mstatus`, implement them in Rust.
2. Make `scause`, `stval`, `ucause` and `utval` writable. 
3. Add some comments for instructions when we need to update this crate into privileged version v1.12.
For part 2, these registers are defined read-write in specification, and are typically read in supervisor S-level. However in M-level there are some situations we should write values into them. This feature is used when M-level environment are transfering exception to S-level kernel.
Function `scause::set` contains somehow lots of code here, we need to write a `Trap` struct into it, but I don't know which way is the best to implement this function.
=> Small fixes according to RISC-V privileged specification

src/register/mcounteren.rs, src/register/scounteren.rs
When running `cargo doc` on this crate and crates depends on this crate, cargo will always raise `unresolved link` warnings for those `[h]` and `[x]`, which is annoying.
This pr escaped the `[` and `]` in these code to silence these warning.
=> Fix unescaped "[]"s in doc comment

README.md
Fixes link to properly direct to heading in wg repo README.md.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
=> Fix link to RISC-V team in wg repo

src/register/satp.rs, src/register/scause.rs, src/register/stval.rs, src/register/ucause.rs, src/register/utval.rs
This pull request contains:
1. Use `#[cfg(target_pointer_width = "32")]` other than `#[cfg(riscv32)]` to provide support on IDE lint and cargo doc outputs
2. Add `#[inline]` on most of `set` and `write` functions
=> Fix register configuration and documents

src/register/scause.rs
This pull request includes a bug fix. On RISC-V's cause register, first bit means is this cause an interrupt. The code before made a mistake to or an one bit when exception. After this fix, it correctly or an one bit when interrupt.
Related to https://github.com/luojia65/rustsbi/issues/10. Thank you @wyfcyx
=> Bug fix for interrupt bit in `scause::set`

CHANGELOG.md, Cargo.toml
This pull request changes build targets when build documents on `docs.rs`, it will show RISC-V targets other than default x86 targets.
Before:
After (take `rustsbi` crate as example):
=> Add docs.rs document build metadata for build targets

CHANGELOG.md, src/asm.rs, src/lib.rs, src/register/macros.rs
The new `asm` macro has been merged into `nightly` for some time, while `llvm_asm` will be gradually deprecated and will not enter `stable`. This PR replaces `llvm_asm` with `asm`, but there are still some minor issues to discuss.
My reference are:
- [asm feature](https://doc.rust-lang.org/unstable-book/library-features/asm.html)
- [arch/cortex-m: change a few llvm_asm!s to asm!s](https://github.com/tock/tock/pull/2092)
- [Convert all uses of llvm_asm! to asm!](https://github.com/rust-lang/stdarch/pull/1052)
---
In the new `asm` feature, there are several options can set to optimize codes. [options](https://doc.rust-lang.org/unstable-book/library-features/asm.html#options-1)
However, I'm not quite sure which options to set. (Sort of newbie to asm in rust)
=> feat: Use new asm! instead of llvm_asm!

src/asm.rs
There is a bug about the operand order of `riscv::asm::sfence_vma(asid: usize, addr: usize)`. According to [riscv-isa-manual](https://github.com/riscv/riscv-isa-manual/blob/master/src/supervisor.tex#L1198), the first operand should be `vaddr`, and the second be `asid`. But `riscv::asm::sfence_vma` generates assembly code in the reverse order. In fact, our rust-OS which using this instruction to flush TLB have been running into an error until we reverse the parameter order.
I propose a simple solution which leave the function parameter order unchanged. Maybe you guys will change it to be more consistent with the specification. Anyway, let's fix this bug.
=> Bug fix: sfence.vma - incorrect operand order

src/lib.rs, src/macros.rs
professionally copied this macro from the cortex-m crate
=> add singleton macro

.github/workflows/ci.yaml, src/asm.rs, src/lib.rs, src/register/macros.rs
https://github.com/rust-embedded/riscv/pull/86 introduced new `asm!` syntax which is enabled with the `inline-asm` feature. However, it doesn't work with current nightly since `asm_const` unstable feature is not enabled. This PR fixes the problem and adds automatic checks to CI.
=> Add inline-asm build to CI, fix build

CHANGELOG.md, src/delay.rs, src/interrupt.rs, src/register/fcsr.rs, src/register/marchid.rs, src/register/mcause.rs, src/register/mimpid.rs, src/register/misa.rs, src/register/mtvec.rs, src/register/mvendorid.rs, src/register/scause.rs, src/register/stvec.rs, src/register/utvec.rs
This pull request adds missing `#[inline]` flags on field read functions and type conversations. Field `#[inline]` marks to enable inline function optimization which speed up the code when used to build kernels and hypervisors.
Please hint me if there are more missing `#[inline]` flags in project `riscv` so I may include them in this fix too.
Off topic: would it be the time to release a 0.7.1 version now? Then we do not need to pin to commit numbers when developing risc-v projects.
r? @Disasm
=> csr: inline register reads and type conversations

CHANGELOG.md, src/asm.rs
I noticed that a small example using two `asm::delay()` calls worked fine in debug mode but not in release mode. Eventually @jamesmunns spotted that the count register wasn't being reloaded between calls:
```
400001ce:	02faf637          lui	a2,0x2faf
400001d2:	0816061b          addiw	a2,a2,129
400001d6:	c10c              sw	a1,0(a0)
400001d8:	167d              addi	a2,a2,-1
400001da:	fe7d              bnez	a2,400001d8 <.LBB0_8+0x30>
400001dc:	00052023          sw	zero,0(a0) # 2000000 <.Lline_table_start0+0x1fff7a4>
400001e0:	167d              addi	a2,a2,-1
400001e2:	fe7d              bnez	a2,400001e0 <.LBB0_8+0x38>
400001e4:	bfcd              j	400001d6 <.LBB0_8+0x2e>
```
By changing the register spec to `inout`, Rust knows the register is modified and reloads it next time. I added the …
=> Fix asm::delay not clobbering count register

src/delay.rs
Took me a minute or two to figure out what value exactly to pass to `McycleDelay::new`, so figured I'd make a quick PR to add a note for anyone else that hits the same confusion as I did. Also added a doc line for the `delay` module while I was at it, as it was missing one.
=> Add extra documentation for `delay`

src/register/marchid.rs, src/register/mimpid.rs
It seems to have been a copy-paste error.
We ran into a very nasty bug in oreboot on the Allwinner D1 (C906) where
an errata patch in Linux relies on those two being zero.
Signed-off-by: Daniel Maslowski <info@orangecms.org>
=> fix reading marchid and mimpid

src/register/mip.rs
closes #62
In RISC-V privileged specification, it says:
> Bits mip.MTIP and mie.MTIE are the interrupt-pending and interrupt-enable bits for machine timer interrupts. MTIP is read-only in mip, and is cleared by writing to the memory-mapped machine-mode timer compare register.
>
> Bits mip.MSIP and mie.MSIE are the interrupt-pending and interrupt-enable bits for machine-level software interrupts. MSIP is read-only in mip, and is written by accesses to memory-mapped control registers, which are used by remote harts to provide machine-level interprocessor interrupts.
indicated by the specification, mip.MSIP and mip.MTIP bits are read-only. This pull request clearifies this by removing {set, clear}_{msoft, mtimer} functions from mip module of riscv crate.
=> fix: clearify that mip.{MSIP, MTIP} are read-only

Cargo.toml, src/interrupt.rs, src/lib.rs
This shouldn't be a breaking change since Edition 2021 came out in
Rust 1.56, and MSRV is already higher than that (Rust 1.59)
=> Update to edition 2021.

CHANGELOG.md, Cargo.toml
The `riscv` crate includes an important fix (https://github.com/rust-embedded/riscv/pull/107) where the RustSBI community would leverage the use of. However, the latest release v0.8.0 did not include this fix. In this pull request we want to propose to release a new version of `riscv` crate to include at least this fix, so that RustSBI community would write correct implemenations based on this crate.
Notes to `CHANGELOG.md`: the release date `2022-10-06` can always be changed.
r? @Disasm
=> Propose to release a version `riscv` v0.8.1

CHANGELOG.md, Cargo.toml
As per discussion on https://github.com/rust-embedded/riscv/pull/112 we want to release `v0.9.0` and yank `v0.8.1` since the removals were a breaking change.
=> bump version to v0.9.0 due to breaking changes

.github/workflows/ci.yaml, CHANGELOG.md, Cargo.toml, src/critical_section.rs, src/interrupt.rs, src/lib.rs, src/macros.rs
~~Requires #109~~
This adds a [critical-section](https://github.com/rust-embedded/critical-section) implementation for single-core chips, based on disabling all interrupts.
`interrupt::free` is is unsound on multicore systems because it only disables interrupts in the
current core. For multicore chips, a chip-specific critical section implementationis needed instead. Unsoundness is fixed by not returning the `CriticalSection` token.
This is a breaking change.
This is the riscv equivalent of https://github.com/rust-embedded/cortex-m/pull/447 and https://github.com/rust-embedded/cortex-m/pull/448
=> Add critical-section 1.0 implementation, fix multicore unsoundness.

src/critical_section.rs
This changes `SingleHartCriticalSection::acquire` to be done in an atomic way.
Fixes #116
NOTE: no changelog since it fixes a small bug on unreleased change
=> fix atomicity of critical section, fixes #116

CHANGELOG.md, src/critical_section.rs
It should be `0b1000` rather than `0b100`. `Bit 2` is a reserved bit, and `Bit 3` is `MIE` that needs to be cleared.
=> fix critial section implementation

.github/workflows/clippy.yaml, src/lib.rs, src/register/mcounteren.rs, src/register/mstatus.rs, src/register/pmpcfgx.rs, src/register/scause.rs, src/register/scounteren.rs, src/register/sstatus.rs
I've been working with this crate for a while and noticed that it didn't include clippy as part of the CI process. This PR checks that clippy does not trigger any warning for new contributions. I also ran `cargo clippy --fix` to "fix" the crate.
If you think this is useful, I can adapt other repos (e.g., riscv-rt or e310x). Cheers!
=> Added clippy to the CI workflow

CHANGELOG.md, Cargo.toml, src/lib.rs, src/macros.rs, src/peripheral.rs, src/peripheral/plic.rs
Same as #125 (closing right now) but with a clean commit history. I've been playing around with this implementation and detected nice-to-have features and boring patterns that could be implemented using macros. Pointers to repos that are already working with it:
- [`e310x` PAC](https://github.com/greenlsi/e310x)
- [`e310x-hal` HAL](https://github.com/greenlsi/e310x-hal)
- [`hifive1` BSP](https://github.com/romancardenas/hifive1) with an illustrative [example](https://github.com/romancardenas/hifive1/blob/master/examples/interrupt.rs)
=> PLIC peripheral

.github/bors.toml, .github/workflows/build.yaml, .github/workflows/ci.yaml, .github/workflows/clippy.yaml, .github/workflows/rustfmt.yaml, CHANGELOG.md
With all the bors thing going on, I've been reading a bit about merge queues etc. and noticed that some of our workflows still use outdated/deprecated actions. This PR fixes this.
=> Update GitHub workflows

.github/bors.toml
Once we have the CI workflows updated and ready for GHMQ... it's time to remove all the bors-related files and configurations. Once this PR is accepted, bors will no longer be required and we can remove it from the repo settings once and for all.
Related PRs and issues: #132 #133 
Check also [this issue](https://github.com/rust-embedded/wg/issues/671) of the wg repo.
=> Remove bors

src/asm.rs
While working on the peripheral stuff, `cargo doc` kept raising a warning with this macro, as it attempted to find a reference in the crate. This PR fix it
=> Skip [] in docs

CHANGELOG.md, src/register/mcause.rs, src/register/scause.rs
I did a rework of `mcause` and `scause` registers to follow the [latest RISC-V specification](https://github.com/riscv/riscv-isa-manual/releases/download/riscv-isa-release-1239329-2023-05-23/riscv-privileged.pdf). Namely, I removed the user-level interrupt sources and fixed a missing exception type in `scause`.
I also used the `From` and `TryFrom` traits, so now the `Interrupt` and `Exception` enumerations are more usable. I plan to re-export these enums in `riscv-rt` to avoid code duplicates and simplify a bit the logic of the runtime.
=> Rework of mcause and scause registers

CHANGELOG.md, Cargo.toml, src/asm.rs
The NOP instruction does not change architecturally visible state, including operations that would break memory safety boundaries; thus `nop` instruction wrapper should be safe to call. The `delay` function uses ADDI and BNE instructions which would form a function internal loop, which is safe under Rust constraints.
This pull request also includes an explanation on NOP instruction under Rust docs, and a small codestyle fix in Cargo.toml file.
I modified internal macro `instruction` to allow wrapping instruction with safe functions. If it's inappropriate, please reply and I'll change to other ways of implementation.
=> asm: set unsafety of `nop` and `delay` functions to safe

.gitignore, CHANGELOG.md, Cargo.toml, src/register/fcsr.rs, src/register/macros.rs, src/register/mcounteren.rs, src/register/medeleg.rs, src/register/mideleg.rs, src/register/mie.rs, src/register/mip.rs, src/register/mstatus.rs, src/register/pmpcfgx.rs, src/register/satp.rs, src/register/scounteren.rs, src/register/sie.rs, src/register/sip.rs, src/register/sstatus.rs, src/register/uie.rs, src/register/uip.rs, src/register/ustatus.rs
I replaced the `bit_field` crate with bit-wise operations. In this way, we avoid needless checks for getting bits from the registers. Now, future versions of the `riscv` crate will be slightly faster (and smaller)
=> Remove bit_field dependency

CHANGELOG.md, src/register.rs, src/register/macros.rs, src/register/misa.rs, src/register/mstatus.rs, src/register/mstatush.rs
Added new fields to `mstatus` register according to the latest RISC-V specification. For RISCV-32, some of the new fields are in a new register, `mstatush`.
=> Rework on misa and mstatus

.github/workflows/changelog.yaml, CHANGELOG.md
Same as [`riscv-rt`](https://github.com/rust-embedded/riscv-rt/pull/124).
=> Add CI for CHANGELOG.md file

.github/workflows/build.yaml, CHANGELOG.md, Cargo.toml, README.md, src/delay.rs
Preparing to support `e-h-1` once we get the first stable version.
Related: #96 and #106
=> Update embedded-hal to 1.0

.github/workflows/riscv-rt.yaml, riscv-rt/CHANGELOG.md, riscv-rt/link.x.in, riscv-rt/src/lib.rs
This PR consists of three major contributions:
- Removed U-mode interrupts, as they are no longer in the standard
- Transition from `Vector` unions to `Option<fn>`. Both are equivalent, as `Option<fn>` exploits a niche optimization that uses `0usize` to represent `None`. However, using `Option`s is more idiomatic than `Union`s
- Added a mechanism to deal with exceptions that is similar to how we treat interrupts. Now, it allow us to define custom exception handlers for standard exception sources.
=> `riscv-rt`: Rework on exception and interrupt handling

riscv-rt/link.x.in
I forgot to remove U-mode interrupts from the linker script.
=> `riscv-rt`: clean linker script

riscv-rt/CHANGELOG.md, riscv-rt/build.rs, riscv-rt/macros/src/lib.rs, riscv-rt/src/lib.rs
This PR adds FPU initialization when compiling with the `f` or `d` extensions, for the implementation of this I have updated the `parse_target` function from `build.rs` to support additional extensions, this is required until this crate is [updated to rust 1.75](https://github.com/rust-lang/rust/pull/116485) at which point we can use `target_feature`.
I added a little macro to help with zeroing registers, if it is preferable though happy to inline the zeroing of registers
I am new to rust & risc-v in general so apologies if there is any obvious mistakes that have been made, your feedback is greatly appreciated.
closes: #157
=> `riscv-rt`: Implement FPU initialization

.github/workflows/riscv.yaml, riscv/CHANGELOG.md, riscv/Cargo.toml, riscv/src/critical_section.rs, riscv/src/interrupt.rs, riscv/src/lib.rs
(I messed up with previous PR)
This PR solves #114
Now, `crate::interrupt` has machine and supervisor modules for M and S mode, respectively.
A new feature `s-mode` reexports the content of the appropriate module in `crate::interrupt`.
I also modified how the critical section is implemented depending on whether the `s-mode` feature has been selected.
=> `riscv`: support for S-mode

riscv/CHANGELOG.md, riscv/src/asm.rs, riscv/src/interrupt.rs
This PR adds a wrapper to trigger environment calls. It also adds a new function for allowing nested interrupts in M and S mode. Nested interrupts are specially useful for RTOSs, as they can implement preemption in this way.
=> `riscv`: ECALL and nested interrupts

riscv-semihosting/CHANGELOG.md, riscv-semihosting/README.md, riscv-semihosting/src/lib.rs
This PR adds a reference to [`semihosting`](https://crates.io/crates/semihosting) in the `README.md` file, as this crate is preferred over `riscv-semihosting`.
I also addressed @taiki-e 's comments on #170 . (@taiki-e , could you take a look to confirm the issues are fixed?)
=> `riscv-semihosting`: bug fixes

riscv-rt/CHANGELOG.md, riscv-rt/Cargo.toml, riscv-rt/src/lib.rs
This PR solves #152
It uses the [`links`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-links-field) field in the `Cargo.toml` to avoid linking multiple versions of `riscv-rt`.
=> `riscv-rt`: add links to Cargo.toml

riscv-semihosting/Cargo.toml, riscv/CHANGELOG.md, riscv/Cargo.toml, riscv/src/register/misa.rs
Update dependency embedded-hal to version 1.0.0.
There are also small fixes on document tests in file `misa.rs` and Cargo.toml code styles.
=> lib: update dependency embedded-hal to 1.0.0

riscv-pac/CHANGELOG.md, riscv-rt/CHANGELOG.md, riscv-rt/Cargo.toml, riscv-rt/macros/Cargo.toml, riscv-semihosting/CHANGELOG.md, riscv-semihosting/Cargo.toml, riscv-semihosting/src/lib.rs, riscv/CHANGELOG.md, riscv/Cargo.toml
It is time to start releasing the latest changes (specially after e-h-1), as some people are struggling with their builds.
Please, take a quick look and let's publish the current state of this workspace in crates.io
=> Release new versions

riscv-rt/CHANGELOG.md, riscv-rt/build.rs, riscv-rt/src/asm.rs
Motivated by #175 , I added a provisional patch to prevent LLVM from logging spurious errors when compiling for targets with certain extensions (e.g., M or G) in release mode. The patch already contains documentation and pointers to related issues.
=> Avoid spurious errors from LLVM

riscv-rt/CHANGELOG.md, riscv-rt/src/lib.rs
Added an implementation of `default_mp_hook` even when `single-hart` feature is enabled. This is required to avoid linker errors in Nightly builds.
=> `riscv-rt`: Fix nightly builds

riscv/CHANGELOG.md, riscv/src/asm.rs
`sfence.vma`, `fence` and `fence.i` just add ordering constraints load/store operations (between themselves, or other kinds of memory access). There's no risk of any UB or other unexpected visible changes in machine state, so we can make these "safe".
Fixes https://github.com/rust-embedded/riscv/issues/179
=> Make fence operations safe

riscv-pac/CHANGELOG.md, riscv-peripheral/CHANGELOG.md, riscv-peripheral/Cargo.toml, riscv-rt/CHANGELOG.md, riscv-rt/Cargo.toml, riscv-rt/src/lib.rs, riscv/CHANGELOG.md, riscv/Cargo.toml, riscv/src/asm.rs
Minor releases with the changes of the latest PRs. I also made `asm::wfi` safe, following the criteria of `cortex-m`. Additionally, the `riscv-peripheral` crate is ready for its first release.
I will publish these new releases as soon as the PR gets merged.
=> Release new `riscv-peripheral` crate and minor patches

riscv-peripheral/Cargo.toml
Forgot about Cargo metadata and I cannot publish it yet 😥
=> Cargo metadata for riscv-peripheral

riscv-rt/CHANGELOG.md, riscv-rt/link.x.in, riscv-rt/src/asm.rs, riscv-rt/src/lib.rs
Alternative to #188
The `_pre_init_trap` is now weak, and users can override it.
Additionally, all `default_*` and `Default*` symbols are no longer required, since their `_*` version is now a weak symbol written in assembly. In this way, we could slightly reduce the size of the binaries.
Closes #155, closes #156, closes #188
=> `riscv-rt`: `_pre_init_trap` and weak symbols

riscv/CHANGELOG.md
My last PR put the change in the wrong place - it should have gone under "unreleased"
=> Fix mistake in changelog

riscv-rt/CHANGELOG.md, riscv-rt/src/asm.rs
Now, `abort` is a weak symbol. In this way, it is possible to link `riscv-rt` with third-party libraries that define this symbol (e.g., newlib).
Closes #197
=> `riscv-rt`: make `abort` weak

riscv/CHANGELOG.md, riscv/src/register/macros.rs
Exports macros from the `riscv::register::macros` module for external users.
This allows external users to define custom CSR accessor functions.
This is useful for platforms and SoCs with custom CSR registers not defined in the `riscv` crate.
Resolves: #187
=> `riscv`: register: exports macros for custom CSRs

riscv-rt/CHANGELOG.md, riscv-rt/build.rs, riscv-semihosting/CHANGELOG.md, riscv-semihosting/build.rs, riscv/CHANGELOG.md, riscv/build.rs
Change which Cargo `CFG` environment variables are used to select the custom `cfg` variables.
See https://github.com/rust-embedded/riscv/pull/204#issuecomment-2094089195 for discussion.
=> riscv: build: make `cfg` variables more robust

riscv/CHANGELOG.md, riscv/src/register/pmpcfgx.rs
It's useful to be able to do equality tests for these for unit tests.
Should we do this more consistently?
=> Implement Eq and PartialEq for Range and Permission

riscv/src/register/macros.rs
Uses a conditional compilation selector set by modern compiler versions for code gated behind a target architecture.
=> `riscv`: register: fix target architecture conditional compilation

riscv/CHANGELOG.md, riscv/src/bits.rs, riscv/src/lib.rs, riscv/src/register/macros.rs, riscv/src/register/misa.rs, riscv/src/register/mstatus.rs
Without needing to touch the CSR. This allows multiple changes in a single register write.
=> Add Mstatus helpers to allow setting fields in Mstatus

.github/workflows/riscv-rt.yaml, riscv-rt/CHANGELOG.md, riscv-rt/Cargo.toml, riscv-rt/examples/empty.rs, riscv-rt/link.x.in, riscv-rt/macros/Cargo.toml, riscv-rt/macros/src/lib.rs, riscv-rt/src/asm.rs, riscv-rt/src/lib.rs
I am working on providing support for interrupt dispatching in vectored mode. This is a first draft, and I could not test yet if it works. However, I wanted to share it with you so I can start getting some feedback and suggestions about different design decisions. So, the main changes are:
- New `v-trap` feature to enable vectored mode. If this feature is enabled, the assembly code will add a trap vector with `j` instructions to a different trap per interrupt source. Some targets do not implement the standard interrupt convention (e.g., ESP32C3). That is why I left the table as weak. PACs will be able to replace this table accordingly.
- New `interrupt` procedural macro to implement interrupt handlers. Currently, in direct mode, this macro is quite dummy. However, I plan to add some …
=> `riscv-rt`: Support for vectored mode interrupt handling

riscv-rt/macros/src/lib.rs
While testing the new v-trap implementation from https://github.com/rust-embedded/riscv/pull/200 I noticed that upon trapping a vectored interrupt, the program counter ends up halfway between instructions right before `_start_DefaultHandler_trap` causing an illegal instruction exception.
The cause seems to be that this location (`_start_DefaultHandler_trap`) is reached via direct unconditional jump in `_continue_interrupt_trap` and the jump instruction is taken at 4-byte alignment. Setting these symbols to .align 4 fixes the problem on our (custom) machine.
I think it's a feature of RISC-V unconditional jumps that they can't express addresses below 4-byte alignment but it could be a feature(bug) of our machine as well. I'm a bit confused about this still because the disassembly shows the …
=> Align jump targets to 4 bytes

riscv/CHANGELOG.md, riscv/src/register/mstatus.rs
Fixes the assignment in the `mstatus` unti tests.
=> fixup: riscv: fix `mstatus` test

riscv-peripheral/CHANGELOG.md, riscv-peripheral/src/lib.rs, riscv/CHANGELOG.md, riscv/src/interrupt.rs, riscv/src/register.rs, riscv/src/register/mcountinhibit.rs
Adds the `riscv::register::mcountinhibit` module for the `mcountinhibit` CSR.
=> riscv: add `mcountinhibit` module

riscv-semihosting/CHANGELOG.md, riscv-semihosting/src/debug.rs
QEMU's handler for REPORT_EXCEPTION (a.k.a. TARGET_SYS_EXIT in QEMU sources) expects two arguments for 64-bit systems, including riscv64. In the event that a second argument is not provided, QEMU takes an error path which does *not* exit the simulation.
The net result is that semihosting::debug::exit() hangs on riscv64 qemu simulation.
Provide the necessary extra parameter to the syscall so that exit now works properly.
Note that the second parameter only affects the simulator exit code if the first parameter is ApplicationExit, and we use ApplicationExit only for successful exit, so we can simply hardcode 0 as second parameter. On the error path we set first parameter to RunTimeErrorUnknown and QEMU properly returns exit code 1 regardless of second parameter
.Note: tested for both rv32 …
=> Fix semihosting::debug::exit() on riscv64 QEMU targets.

riscv/CHANGELOG.md, riscv/src/register/mcounteren.rs
Adds functions for updating the in-memory `Mcounteren` structure without touching the CSR.
Allows manipulating all bitfields in-memory, and writing the entire value back to the CSR at once.
=> riscv: add `mcounteren` in-memory update functions

.github/workflows/riscv-rt.yaml, riscv-rt/CHANGELOG.md, riscv-rt/Cargo.toml, riscv-rt/README.md, riscv-rt/macros/Cargo.toml, riscv-rt/src/lib.rs
Upgrade `syn` in order to deduplicate dependencies in projects depending on `riscv-rt`, as most other crates have upgraded to version 2.
Tested by building and flashing a simple hello world to the ESP32-C3, with no difference between the two versions.
While syn's [README](https://github.com/dtolnay/syn/blob/master/README.md) states `Version requirement: Syn supports rustc 1.61 and up.`, riscv-rt-macros still builds with `1.59`.
=> riscv-rt-macros: update syn to v2.0

riscv-pac/CHANGELOG.md, riscv-pac/src/lib.rs, riscv-pac/src/result.rs, riscv-peripheral/CHANGELOG.md, riscv-peripheral/examples/e310x.rs, riscv-peripheral/src/aclint.rs, riscv-peripheral/src/macros.rs, riscv-peripheral/src/plic.rs, riscv/CHANGELOG.md, riscv/Cargo.toml, riscv/src/lib.rs, riscv/src/register/macros.rs, riscv/src/register/mcounteren.rs, riscv/src/register/mcountinhibit.rs, riscv/src/register/pmpcfgx.rs, riscv/src/register/satp.rs, riscv/src/register/scounteren.rs
Adds fallible variants to all functions that explicitly panic in the `riscv` crate.
Resolves: https://github.com/rust-embedded/riscv/issues/212
=> riscv: add fallible functions

riscv-semihosting/CHANGELOG.md, riscv-semihosting/src/lib.rs
Fix the following warning when generating the crate documentation:
```
warning: `syscall` is both a function and a macro
--> riscv-semihosting/src/lib.rs:212:15
|
212 | /// Same as [`syscall`].
|               ^^^^^^^ ambiguous link
|
= note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
help: to link to the function, add parentheses
|
212 | /// Same as [`syscall()`].
|                      ++
help: to link to the macro, add an exclamation mark
|
212 | /// Same as [`syscall!`].
|                      +
```
=> riscv-semihosting: fix ambiguous documentation link

.github/workflows/riscv-rt.yaml, riscv-rt/CHANGELOG.md, riscv-rt/Cargo.toml, riscv-rt/macros/Cargo.toml, riscv-rt/macros/src/lib.rs, riscv-rt/src/asm.rs, riscv-rt/src/lib.rs, riscv/src/interrupt.rs
U-Boot passes arguments through `int argc` and `char *const argv[]`. In order to work with them riscv-rt should accept appropriate entry point signature. Also because the only way to get boot-hart is through fdt this feature implies single-hart.
Expected entry point signature for u-boot: https://github.com/u-boot/u-boot/blob/master/lib/elf.c#L26
=> Make support for u-boot

riscv/CHANGELOG.md, riscv/src/register/macros.rs, riscv/src/register/marchid.rs
Adds a helper macro to test if a CSR is implemented on the platform.
Uses CSR helper macros to define the `marchid` register.
Related: #229
=> riscv: define marchid using CSR macros

riscv/CHANGELOG.md, riscv/src/register/mcountinhibit.rs
Re-uses the `try_*` functions in their panicking equivalents for a slight code-size reduction.
=> riscv: re-use `mcountinhibit` `try_*` functions

riscv/CHANGELOG.md, riscv/src/register/mcause.rs
Uses CSR helper macros to define the `mcause` register.
Related: #229
=> riscv: define mcause using CSR macros

riscv/CHANGELOG.md, riscv/src/register/medeleg.rs
Uses CSR helper macros to define the `medeleg` register.
Adds basic unit tests for the `medeleg` register.
Related: #229
=> riscv: define medeleg using CSR macros

riscv/CHANGELOG.md, riscv/src/register/macros.rs, riscv/src/register/medeleg.rs, riscv/src/register/mideleg.rs
Uses CSR helper macros to define the `mideleg` register.
Adds basic unit tests for the `mideleg` register.
Related: https://github.com/rust-embedded/riscv/issues/229
=> riscv: define mideleg using CSR macros

riscv/CHANGELOG.md, riscv/src/register/macros.rs, riscv/src/register/mcounteren.rs
Uses CSR helper macros to define the `mcounteren` register.
Related: #229
=> riscv: use CSR macros for mcounteren

riscv/CHANGELOG.md, riscv/src/register/mie.rs
Uses CSR helper macros to define the `mie` register.
Adds basic unit tests for the `mie` register.
=> riscv: define mie using CSR macros

riscv-rt/CHANGELOG.md, riscv-rt/Cargo.toml, riscv-rt/link.x.in, riscv-rt/src/asm.rs, riscv-rt/src/lib.rs
Looks like the current linker file contains some things that were probably required when using binary blobs in `riscv-rt`. Now that we use inline assembly, they are not needed. Furthermore, some of them appear to provoke errors.
This PR (still WIP) aims to fix these issues. For instance, just commenting out the `eh_frame` part of the linker script fixes the compilation of the example provided in #196 
I still need to play around with this, but this is a good first step
Closes #196
=> Fix linker file for RISCV-64 targets

riscv/CHANGELOG.md, riscv/src/register/mimpid.rs
Uses CSR helper macros to define the `mimpid` register.
Related: #229
=> riscv: define mimpid using CSR macros

riscv/CHANGELOG.md, riscv/src/register/macros.rs, riscv/src/register/misa.rs, riscv/src/register/mstatus.rs, riscv/src/register/sstatus.rs, riscv/src/register/tests/read_only_csr.rs, riscv/src/register/tests/read_write_csr.rs, riscv/src/register/tests/write_only_csr.rs
Removes the unused field range arguments from the CSR field enum helper macro.
Uses CSR helper macros to define the `misa` register.
Corrections for other users of the `XLEN` enum.
Adds basic unit tests for the `misa` register.
Related: #229
=> riscv: define misa using CSR macros

riscv/CHANGELOG.md, riscv/src/register/mip.rs
Uses CSR helper macros to define the `mip` register.
Adds basic unit tests for the `mip` register.
Related: https://github.com/rust-embedded/riscv/issues/229
=> riscv: define mip using CSR macros

.github/workflows/changelog.yaml, .github/workflows/riscv-rt.yaml, .github/workflows/riscv-target-parser.yaml, Cargo.toml, README.md, riscv-rt/CHANGELOG.md, riscv-rt/Cargo.toml, riscv-rt/build.rs, riscv-rt/macros/Cargo.toml, riscv-rt/macros/src/lib.rs, riscv-rt/src/asm.rs, riscv-rt/src/interrupts.rs, riscv-rt/src/lib.rs, riscv-target-parser/CHANGELOG.md, riscv-target-parser/Cargo.toml, riscv-target-parser/README.md, riscv-target-parser/src/extension.rs, riscv-target-parser/src/lib.rs
Avoids using `x16`+ registers in assembly code. This is necessary to provide compatibility with RV32E.
Note that there is still work to do. Namely, the trap frame must adapt to the target base instruction set.
Solves #189 
Related: #239
=> `riscv-rt`: compatibility with RV32E and RV64E

riscv/CHANGELOG.md, riscv/src/lib.rs, riscv/src/register/macros.rs, riscv/src/register/mstatus.rs
Adds an optional field documentation macro argument to allow adding documentation to CSR field enum variants.
Current macros for CSR field enum accessors allow for the MSB and LSB to hold the same value (for single-bit enum fields).
Clippy defaults to `deny(clippy::eq_op)`. The simplest solution is to allow the lint. A more robust solution is to special-case equal operands with new macro arm.
Uses CSR macro helpers to define the `mstatus` CSR register.
Adds a CSR test field macro arm for enum fields.
Adds more unit test cases for `Mstatus` field accessors.
=> riscv: define mstatus using CSR macro

riscv/CHANGELOG.md, riscv/src/asm.rs
Closes #181 
I decided to keep instructions that trigger exceptions (e.g., `ecall`) `unsafe` for their potential side effects. For example, if no exception handler is defined, triggering an exception can cause the program to crash. Also, raising exceptions is a potential way to avoid critical sections. Thus, one must be careful with them.
In any case, I'm open to to discuss this in case anyone has a different point of view.
=> `riscv`: align assembly functions with `cortex-m`

riscv/CHANGELOG.md, riscv/src/register/mstatush.rs
Uses CSR macro helpers to define the `mstatush` CSR register.
Adds a basic unit-tests for the `mstatush` CSR.
=> riscv: define `mstatush` CSR with macro helpers

riscv/CHANGELOG.md, riscv/src/register/macros.rs
I added a `cfg` field and some recursive macro calls to reduce duplicates in register macros.
=> Simplify register macros

riscv-rt/CHANGELOG.md, riscv-rt/link.x.in
Note sure why the `. = ALIGN(${ARCH_WIDTH});` before `__ebss = .;` doesn't also align `.heap`.
```toml
[package]
name = "foo"
version = "0.1.0"
edition = "2024"
[dependencies]
critical-section = "1.2.0"
embedded-alloc = "0.6.0"
riscv = { version = "0.12.1", features = ["critical-section-single-hart"] }
[dependencies.riscv-rt]
git = "https://github.com/rust-embedded/riscv.git"
rev = "fe6da179b437f23545a5db13ead28dc9855523a4"
```
```text
MEMORY {
FLASH (RX) : ORIGIN = 0x20000000, LENGTH = 0x80000
RAM    (W) : ORIGIN = 0x10000000, LENGTH = 0x20000
}
REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);
_heap_size = 0x10000;
```
```rust …
```
=> Make sure .heap is 4-byte aligned

riscv/CHANGELOG.md, riscv/src/register/mvendorid.rs
Uses CSR macro helpers to define the `mvendorid` CSR register.
=> riscv: define mvendorid CSR with macro helpers

riscv-rt/CHANGELOG.md, riscv-rt/build.rs, riscv-rt/src/interrupts.rs, riscv/CHANGELOG.md, riscv/macros/src/lib.rs
The RISC-V Privileged Specification (version 1.11) for mtvec CSR says:
> The value in the BASE field must always be aligned on a 4-byte boundary, and the MODE setting may
> impose additional alignment constraints on the value in the BASE field.
> [...]
> An implementation may have different alignment constraints for different modes. In particular,
> MODE=Vectored may have stricter alignment constraints than MODE=Direct.
The Ibex Reference Guide for mtvec CSR says[^1]:
> The trap-vector base address, always aligned to 256 bytes
Other implementations have yet other alignment constraints (see https://github.com/rust-embedded/riscv/pull/259#issuecomment-2602810245).
This PR introduces the `RISCV_MTVEC_ALIGN` environment variable to let users (in particular PACs) choose the alignment …
=> riscv-rt: Add RISCV_MTVEC_ALIGN to control the alignment of the vector table

riscv/CHANGELOG.md, riscv/src/register/macros.rs, riscv/src/register/satp.rs
Uses CSR macro helpers to define the `satp` CSR register.
Changes the CSR number + mask macro arguments into `expr` to allow for definitions using constants and type expressions.
Adds basic unit tests for the `satp` CSR.
=> riscv: define satp CSR with macro helpers

riscv/CHANGELOG.md, riscv/src/register/pmpcfgx.rs
Uses CSR helper macros to define `pmpcfgx` field types.
=> riscv: define `pmpcfgx` types with CSR macros

riscv/CHANGELOG.md, riscv/src/register/macros.rs
Closes #209 
**Work in Progress!** I added a `safe` pattern to opt out of unsafety in cases where we consider there to be no safety issues. I will list all the different registers where we use this macro and nominate some to maintain write safety.
=> Make all CSR writes unsafe by default

riscv/CHANGELOG.md, riscv/src/register/scause.rs
Uses CSR macro helpers to define the `scause` CSR register.
Adds basic unit tests for the `scause` CSR.
Related: #229
=> riscv: define `scause` CSR with macro helpers

riscv/CHANGELOG.md, riscv/src/register/sie.rs
Uses CSR macro helpers to define the `sie` CSR register.
Adds basic unit tests for the `sie` CSR.
Related: #229
=> riscv: define `sie` CSR with macro helpers 

riscv/CHANGELOG.md, riscv/src/register/scounteren.rs, riscv/src/register/tests/read_write_csr.rs, riscv/src/register/tests/write_only_csr.rs
Uses CSR macro helpers to define the `scounteren` CSR register.
Adds basic unit tests for the `scounteren` CSR.
Related: #229
=> riscv: define `scounteren` CSR with macro helpers

riscv/CHANGELOG.md, riscv/src/register/sip.rs
Uses CSR macro helpers to define the `sip` CSR register.
Adds basic unit tests for the `sip` CSR.
Related: https://github.com/rust-embedded/riscv/issues/229
=> riscv: define `sip` CSR with macro helpers

riscv/CHANGELOG.md, riscv/src/register/sstatus.rs
Uses CSR macro helpers to define the `sstatus` CSR register.
Adds basic unit tests for the `sstatus` CSR.
Related: #229
=> riscv: define `sstatus` CSR with macro helpers

riscv/CHANGELOG.md, riscv/src/register/stvec.rs
Uses CSR macro helpers to define the `stvec` CSR register.
Adds basic unit tests for the `stvec` CSR.
Related: #229
=> riscv: define `stvec` CSR with macro helpers 

riscv/CHANGELOG.md, riscv/src/register/pmpcfgx.rs
Adds the remaining `pmpcfg` CSRs from the RISC-V privileged specification.
From discussion with @romancardenas: https://github.com/rust-embedded/riscv/pull/257#pullrequestreview-2571862955
=> riscv: add more `pmpcfg` CSRs

riscv/CHANGELOG.md, riscv/src/register/macros.rs, riscv/src/register/mcycle.rs, riscv/src/register/mcycleh.rs, riscv/src/register/minstret.rs, riscv/src/register/minstreth.rs
The RISC-V Instruction Set Manual Volume II: Privileged Architecture 20240411 specifies mcycle and minstret as "MRW" for read-write, instead of "MRO" for read-only. Therefore these registers should be writable.
Quick question: should there be also a `write_composite_csr` function for these registers since they are 64-bit registers even on 32-bit targets? That macro didn't exist so far but I could add it. Notably, just being able to write the lower bits is useful.
=> riscv: make mcycle & minstret writable

.github/workflows/tests.yaml, riscv-rt/CHANGELOG.md, riscv-rt/build.rs, riscv-rt/exceptions.x, riscv-rt/interrupts.x, riscv-rt/link.x.in, riscv-rt/macros/src/lib.rs, tests/Cargo.toml, tests/tests/riscv-rt/core_interrupt/fail_signatures.stderr, tests/tests/riscv-rt/exception/fail_signatures.stderr, tests/tests/riscv-rt/external_interrupt/fail_signatures.stderr
As now core interrupts and exceptions can be re-defined in PACs to adapt to different targets, I thought it would be a good idea to clean the linker script and only add weak bindings to standard exceptions and interrupts when these are not disabled via the `no-exceptions` and `no-interrupts` features.
Now, in the `build.rs` script, we check if the `no-interrupts` and `no-exceptions` features are enabled. If not, we copy-paste the content of the new `interrupts.x` and `exceptions.x` files, respectively.
This is not a breaking change, it should work the same way. In fact, it might help find bugs in PACs that define partially their custom interrupt or exceptions.
=> `riscv-rt`: add interrupts and exceptions to `link.x` only when required

riscv-target-parser/CHANGELOG.md, riscv-target-parser/Cargo.toml, riscv-target-parser/src/extension.rs
When the target has extensions starting from z,s,x the extension extraction fails
=> Fix for extraction of extensions starting with 's'/ 'x'/ 'z' 

riscv-rt/CHANGELOG.md, riscv-rt/link.x.in, riscv-rt/src/asm.rs, riscv-rt/src/lib.rs, riscv-target-parser/CHANGELOG.md, riscv-target-parser/src/lib.rs
Following the rework required to close #247 
Now, `_pre_init_trap` defaults to `_default_abort`, which is 4-byte aligned to ensure that we comply with the requirements of the `xtvec` register.
=> _pre_init_trap defaults to _default_abort

riscv/CHANGELOG.md, riscv/src/interrupt/machine.rs
Just simplify the `nested` function for M-mode, following the same fashion as for S-mode.
=> Simplify `riscv::interrupt::machine::nested`

riscv/CHANGELOG.md, riscv/src/register.rs, riscv/src/register/senvcfg.rs
Adds the definition for the `senvcfg` Supervisor configuration CSR.
Adds basic unit tests for the `senvcfg` CSR.
Related: https://github.com/rust-embedded/riscv/issues/1
=> register: add `senvcfg` register

.github/workflows/clippy.yaml, Cargo.toml, riscv-rt/CHANGELOG.md, riscv-rt/Cargo.toml, riscv-rt/macros/src/lib.rs, riscv-rt/src/asm.rs, riscv-rt/src/exceptions.rs, riscv-rt/src/interrupts.rs, riscv-rt/src/lib.rs, tests-build/Cargo.toml, tests-build/src/lib.rs
Still working on #247 
The idea is to remove `__pre_init` from the default `riscv-rt` crate. If users want it, they must enable the `pre-init` feature.
If enabled, no default `__pre_init` symbol is provided, as we assume that users will develop their routine.
Additionally, the `riscv_rt::pre_init` attribute macro is now marked as deprecated, as running Rust code before RAM initialization is unsound, and assembly code is preferred.
=> `riscv-rt`: Leave `__pre_init` under a feature gate

riscv-rt/CHANGELOG.md, riscv-rt/link.x.in, riscv-rt/src/asm.rs
=> `riscv-rt`: Remove weak symbol for _mp_hook

riscv/CHANGELOG.md, riscv/src/register.rs, riscv/src/register/macros.rs, riscv/src/register/mtinst.rs
Adds the definition for the `mtinst` Machine trap instruction CSR.
Adds a test macro branch for multi-bit register fields.
Minor correction to the single-bit test macro for not assuming the field's initial value.
Adds basic unit tests for the `mtinst` CSR.
Related: #1
=> register: add mtinst register

.github/workflows/riscv-rt.yaml, .github/workflows/riscv-semihosting.yaml, .github/workflows/riscv-target-parser.yaml, .github/workflows/riscv.yaml, .github/workflows/tests.yaml, riscv/CHANGELOG.md, riscv/Cargo.toml, riscv/src/register.rs, riscv/src/register/mconfigptr.rs
Adds the definition for the `mconfigptr` Machine configuration pointer CSR.
Adds basic unit tests for the `mconfigptr` CSR.
=> register: add `mconfigptr` register

riscv/CHANGELOG.md, riscv/src/register.rs, riscv/src/register/mtval2.rs
Adds the definition for the `mtval2` Machine trap value 2 CSR.
Adds basic unit tests for the `mtval2` CSR.
Related: #1
=> register: add `mtval2` register

riscv-peripheral/CHANGELOG.md, riscv-peripheral/src/aclint.rs, riscv-peripheral/src/aclint/mswi.rs, riscv-peripheral/src/aclint/mtimer.rs, riscv-peripheral/src/aclint/sswi.rs, riscv-peripheral/src/plic.rs
Adds const methods to access registers for HART 0. This is especially handy for single-HART targets
=> `riscv-peripheral`: const methods for HART 0

riscv/CHANGELOG.md, riscv/src/register/mtvec.rs, riscv/src/register/stvec.rs
Adds a few convenience functions to deal with `mtvec` and `xtvec` registers.
=> `riscv`: add Xtvec::new and Xtvec::try_new

riscv-rt/link.x.in, riscv-rt/src/lib.rs
* Avoids referring to how cargo features work with an example of how to use them for every feature mentioned.
* Mention that no features flags are enabled by default.
* Also: Remove outdated abort comment in `link.x.in`. I couldn't be bothered to open a separate PR for this, hope that's ok.
=> docs(riscv-rt): make feature flag descriptions more succinct

riscv-rt/CHANGELOG.md, riscv-rt/src/asm.rs
Fixes #321
I intentionally didn't update the indentation, for two reasons:
1) I don't even know how this should be indented
2) This way it's easier to review
If you'd prefer some certain way of indenting the conditional blocks inside the `cfg_global_asm!` call, I'll happily update the pull request.
=> Join global_asm macro invocations

riscv-rt/CHANGELOG.md, riscv-rt/link.x.in
I encountered linker errors trying to build RTIC examples on RISC-V. The reason was that the linker could not find any empty spot in RAM to place the `.uninit` section. This PR mimics the `.uninit` section of `cortex-m-rt`. The linker will put it in the same memory region as `.bss`, considering that both sections have a very similar purpose.
=> `riscv-rt`: Add uninit section

riscv/CHANGELOG.md, riscv/src/register/mcause.rs
Set the mcause mask to `!0u64` on rv64 targets.
Fixes #333
=> Allow 64-bit Mcause::from_bits on rv64

.gitignore, riscv/CHANGELOG.md, riscv/src/interrupt/machine.rs, riscv/src/interrupt/supervisor.rs, riscv/src/register/mip.rs, riscv/src/register/sip.rs
The methods for unpending interrupts via xip registers are marked as `unsafe`, as per the RISCV ISA specification:
> "Each individual bit in register mip may be writable or may be read-only. When bit i in mip is writable, a pending interrupt i can be cleared by writing 0 to this bit. If interrupt i can become pending but bit i in mip is read-only, the implementation must provide some other mechanism for clearing the pending interrupt.
Therefore, each platform may provide a safe abstraction of these functions for their target when applies.
=> `riscv`: Use `riscv_pac::CoreInterruptNumber` in `xip` registers

riscv-rt/CHANGELOG.md, riscv-rt/Cargo.toml, riscv-rt/src/interrupts.rs, riscv-rt/src/lib.rs
Not a huge thing but since `Debug` is already implemented on these two types, having `defmt::Format` would be useful (at least for us and at least for `TrapFrame` ).
Given `defmt` is 1.0 this shouldn't be a problem, I guess. Let me know if you want something changed here or if you in general dislike the optional dependency.
=> Optionally implement `defmt::Format`

riscv-rt/CHANGELOG.md, riscv-rt/macros/src/lib.rs, tests-trybuild/tests/riscv-rt/core_interrupt/fail_signatures.stderr, tests-trybuild/tests/riscv-rt/exception/fail_signatures.stderr, tests-trybuild/tests/riscv-rt/external_interrupt/fail_signatures.stderr
This allows `extern "C"` functions for exception, core_interrupt and external_interrupt.
To the extend its used here, C-abi and Rust-abi is same.
The real motivation however is to allow us to use naked-functions on stable (it's not stable for Rust-abi)
=> Allow `extern "C"`

riscv/CHANGELOG.md, riscv/src/register.rs, riscv/src/register/miselect.rs
Adds the `miselect` register for selecting an indirect CSR according to the `Smcsrind` extension.
Related: #1, #226
=> riscv: add the `miselect` CSR

riscv/CHANGELOG.md, riscv/src/asm.rs, riscv/src/register/miselect.rs
- This PR enhances the documentation and code quality of RISC-V assembly instruction wrappers in asm.rs while maintaining full backward compatibility.
- Enhanced safety documentation: Added comprehensive safety sections explaining when and why instructions like ebreak and ecall are unsafe, including specific warnings about exception handling and stack pointer management.
- Expanded behavioral descriptions: Provided detailed explanations of instruction behavior, including privilege mode effects for ecall and power management implications for wfi.
- Added practical use cases: Documented appropriate use cases for fence operations, including multiprocessor considerations and performance implications.
- Improved function parameter documentation: Enhanced documentation for sfence_vma() with …
=> asm: Improve documentation and code quality for RISC-V instructions

riscv-target-parser/CHANGELOG.md, riscv-target-parser/Cargo.toml
This PR prepares to publish a new version of `riscv-target-parser` with the changes on #349 
The idea is publishing it ASAP and yanking its previous version.
=> Publish `riscv-target-parser` patch
